-- MySQL Script generated by MySQL Workbench
-- Thu Jul  7 13:01:13 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CollegeEssentials
-- -----------------------------------------------------
SET SQL_SAFE_UPDATES = 0;
CREATE DATABASE IF NOT EXISTS ebdb; ## name given from AWS
USE ebdb;
-- -----------------------------------------------------
-- Table `GeneralUser`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GeneralUser` ;

CREATE TABLE IF NOT EXISTS `GeneralUser` (
  `general_user_id` INT NOT NULL AUTO_INCREMENT,
  `ip_address` INT NULL,
  PRIMARY KEY (`general_user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RegisteredUser`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RegisteredUser` ;

CREATE TABLE IF NOT EXISTS `RegisteredUser` (
  `registered_user_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(30) NULL,
  `password` VARCHAR(20) NULL,
  `email` VARCHAR(45) NULL,
  `last_name` VARCHAR(30) NULL,
  PRIMARY KEY (`registered_user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Buyer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Buyer` ;

CREATE TABLE IF NOT EXISTS `Buyer` (
  `buyer_id` INT NOT NULL AUTO_INCREMENT,
  `registered_user_id` INT NOT NULL,
  PRIMARY KEY (`buyer_id`, `registered_user_id`),
  INDEX `FK_registeredUser_buyer_idx` (`registered_user_id` ASC) VISIBLE,
  CONSTRAINT `FK_registeredUser_buyer`
    FOREIGN KEY (`registered_user_id`)
    REFERENCES `RegisteredUser` (`registered_user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Seller`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Seller` ;

CREATE TABLE IF NOT EXISTS `Seller` (
  `seller_id` INT NOT NULL AUTO_INCREMENT,
  `registered_user_id` INT NOT NULL,
  PRIMARY KEY (`seller_id`, `registered_user_id`),
  INDEX `FK_registeredUser_seller_idx` (`registered_user_id` ASC) VISIBLE,
  CONSTRAINT `FK_registeredUser_seller`
    FOREIGN KEY (`registered_user_id`)
    REFERENCES `RegisteredUser` (`registered_user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Admin` ;

CREATE TABLE IF NOT EXISTS `Admin` (
  `admin_id` INT NOT NULL AUTO_INCREMENT,
  `registered_user_id` INT NOT NULL,
  PRIMARY KEY (`admin_id`, `registered_user_id`),
  INDEX `FK_registeredUser_admin_idx` (`registered_user_id` ASC) VISIBLE,
  CONSTRAINT `FK_registeredUser_admin`
    FOREIGN KEY (`registered_user_id`)
    REFERENCES `RegisteredUser` (`registered_user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `College`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `College` ;

CREATE TABLE IF NOT EXISTS `College` (
  `college_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NULL,
  PRIMARY KEY (`college_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ServiceListing`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ServiceListing` ;

CREATE TABLE IF NOT EXISTS `ServiceListing` (
  `service_listing_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `description` VARCHAR(1000) NULL,
  `registered_user_id` INT NULL,
  `created_at` TIMESTAMP NULL,
  PRIMARY KEY (`service_listing_id`),
  INDEX `FK_registeredUser_serviceListing_idx` (`registered_user_id` ASC) VISIBLE,
  CONSTRAINT `FK_registeredUser_serviceListing`
    FOREIGN KEY (`registered_user_id`)
    REFERENCES `RegisteredUser` (`registered_user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AssociatedCollege`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AssociatedCollege` ;

CREATE TABLE IF NOT EXISTS `AssociatedCollege` (
  `associated_college_id` INT NOT NULL AUTO_INCREMENT,
  `college_id` INT NOT NULL,
  `registered_user_id` INT NOT NULL,
  PRIMARY KEY (`associated_college_id`),
  INDEX `FK_registeredUser_associatedCollege_idx` (`registered_user_id` ASC) VISIBLE,
  INDEX `FK_college_associatedCollege_idx` (`college_id` ASC) VISIBLE,
  CONSTRAINT `FK_registeredUser_associatedCollege`
    FOREIGN KEY (`registered_user_id`)
    REFERENCES `RegisteredUser` (`registered_user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_college_associatedCollege`
    FOREIGN KEY (`college_id`)
    REFERENCES `College` (`college_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MarketplaceListing`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MarketplaceListing` ;

CREATE TABLE IF NOT EXISTS `MarketplaceListing` (
  `marketplace_listing_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `created_at` TIMESTAMP NULL,
  `body` VARCHAR(1000) NULL,
  `seller_id` INT NOT NULL,
  `price` INT NULL,
  `posted_at` TIMESTAMP NULL,
  PRIMARY KEY (`marketplace_listing_id`),
  INDEX `FK_seller_marketplaceListing_idx` (`seller_id` ASC) VISIBLE,
  CONSTRAINT `FK_seller_marketplaceListing`
    FOREIGN KEY (`seller_id`)
    REFERENCES `Seller` (`seller_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ServiceReply`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ServiceReply` ;

CREATE TABLE IF NOT EXISTS `ServiceReply` (
  `service_reply_id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(1000) NULL,
  `registered_user_id` INT NULL,
  PRIMARY KEY (`service_reply_id`),
  INDEX `FK_registeredUser_serviceReply_idx` (`registered_user_id` ASC) VISIBLE,
  CONSTRAINT `FK_registeredUser_serviceReply`
    FOREIGN KEY (`registered_user_id`)
    REFERENCES `RegisteredUser` (`registered_user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Payment` ;

CREATE TABLE IF NOT EXISTS `Payment` (
  `payment_id` INT NOT NULL AUTO_INCREMENT,
  `payment_type` VARCHAR(45) NULL,
  `card_number` INT NULL,
  PRIMARY KEY (`payment_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Transaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Transaction` ;

CREATE TABLE IF NOT EXISTS `Transaction` (
  `transaction_id` INT NOT NULL AUTO_INCREMENT,
  `completed_at` TIMESTAMP NULL,
  `payment_id` INT NOT NULL,
  `buyer_id` INT NOT NULL,
  `seller_id` INT NOT NULL,
  PRIMARY KEY (`transaction_id`),
  INDEX `FK_payment_transaction_idx` (`payment_id` ASC) VISIBLE,
  INDEX `FK_buyer_transaction_idx` (`buyer_id` ASC) VISIBLE,
  INDEX `FK_seller_transaction_idx` (`seller_id` ASC) VISIBLE,
  CONSTRAINT `FK_payment_transaction`
    FOREIGN KEY (`payment_id`)
    REFERENCES `Payment` (`payment_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_buyer_transaction`
    FOREIGN KEY (`buyer_id`)
    REFERENCES `Buyer` (`buyer_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_seller_transaction`
    FOREIGN KEY (`seller_id`)
    REFERENCES `Seller` (`seller_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShoppingCart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ShoppingCart` ;

CREATE TABLE IF NOT EXISTS `ShoppingCart` (
  `shopping_cart_id` INT NOT NULL AUTO_INCREMENT,
  `registered_user_id` INT NOT NULL,
  PRIMARY KEY (`shopping_cart_id`),
  INDEX `FK_registeredUser_shoppingCart_idx` (`registered_user_id` ASC) VISIBLE,
  CONSTRAINT `FK_registeredUser_shoppingCart`
    FOREIGN KEY (`registered_user_id`)
    REFERENCES `RegisteredUser` (`registered_user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Receipt`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Receipt` ;

CREATE TABLE IF NOT EXISTS `Receipt` (
  `receipt_id` INT NOT NULL AUTO_INCREMENT,
  `transaction_id` INT NOT NULL,
  `buyer_id` INT NOT NULL,
  `seller_id` INT NOT NULL,
  PRIMARY KEY (`receipt_id`),
  INDEX `FK_transaction_receipt_idx` (`transaction_id` ASC) VISIBLE,
  INDEX `FK_buyer_receipt_idx` (`buyer_id` ASC) VISIBLE,
  INDEX `FK_seller_receipt_idx` (`seller_id` ASC) VISIBLE,
  CONSTRAINT `FK_transaction_receipt`
    FOREIGN KEY (`transaction_id`)
    REFERENCES `Transaction` (`transaction_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_buyer_receipt`
    FOREIGN KEY (`buyer_id`)
    REFERENCES `Buyer` (`buyer_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_seller_receipt`
    FOREIGN KEY (`seller_id`)
    REFERENCES `Seller` (`seller_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ratings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ratings` ;

CREATE TABLE IF NOT EXISTS `Ratings` (
  `ratings_id` INT NOT NULL AUTO_INCREMENT,
  `rating` TINYINT(5) NULL,
  `registered_user_sender_id` INT NOT NULL,
  `transaction_id` INT NOT NULL,
  `registered_user_receiver_id` INT NOT NULL,
  `description` VARCHAR(1000) NULL,
  PRIMARY KEY (`ratings_id`, `transaction_id`),
  INDEX `FK_registeredUser_ratings_idx` (`registered_user_sender_id` ASC) VISIBLE,
  INDEX `FK_transaction_ratings_idx` (`transaction_id` ASC) VISIBLE,
  INDEX `FK_registeredUserReceiver_ratings_idx` (`registered_user_receiver_id` ASC) VISIBLE,
  CONSTRAINT `FK_registeredUserSender_ratings`
    FOREIGN KEY (`registered_user_sender_id`)
    REFERENCES `RegisteredUser` (`registered_user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_transaction_ratings`
    FOREIGN KEY (`transaction_id`)
    REFERENCES `Transaction` (`transaction_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_registeredUserReceiver_ratings`
    FOREIGN KEY (`registered_user_receiver_id`)
    REFERENCES `RegisteredUser` (`registered_user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Product` ;

CREATE TABLE IF NOT EXISTS `Product` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `general_type` VARCHAR(45) NULL,
  `product_image` VARCHAR(200) NULL,
  `product_condition` VARCHAR(15) NULL,
  PRIMARY KEY (`product_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ServiceTies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ServiceTies` ;

CREATE TABLE IF NOT EXISTS `ServiceTies` (
  `service_ties_id` INT NOT NULL AUTO_INCREMENT,
  `service_listing_id` INT NOT NULL,
  `service_reply_id` INT NOT NULL,
  PRIMARY KEY (`service_ties_id`),
  INDEX `FK_serviceListing_serviceTies_idx` (`service_listing_id` ASC) VISIBLE,
  INDEX `FK_serviceReply_serviceTies_idx` (`service_reply_id` ASC) VISIBLE,
  CONSTRAINT `FK_serviceListing_serviceTies`
    FOREIGN KEY (`service_listing_id`)
    REFERENCES `ServiceListing` (`service_listing_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_serviceReply_serviceTies`
    FOREIGN KEY (`service_reply_id`)
    REFERENCES `ServiceReply` (`service_reply_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UserPayment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UserPayment` ;

CREATE TABLE IF NOT EXISTS `UserPayment` (
  `user_payment_id` INT NOT NULL AUTO_INCREMENT,
  `buyer_id` INT NOT NULL,
  `payment_id` INT NOT NULL,
  PRIMARY KEY (`user_payment_id`),
  INDEX `FK_payment_userPayment_idx` (`payment_id` ASC) VISIBLE,
  INDEX `FK_buyer_userPayment_idx` (`buyer_id` ASC) VISIBLE,
  CONSTRAINT `FK_buyer_userPayment`
    FOREIGN KEY (`buyer_id`)
    REFERENCES `Buyer` (`buyer_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_payment_userPayment`
    FOREIGN KEY (`payment_id`)
    REFERENCES `Payment` (`payment_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProductOrders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProductOrders` ;

CREATE TABLE IF NOT EXISTS `ProductOrders` (
  `product_order_id` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT NOT NULL,
  `buyer_id` INT NOT NULL,
  PRIMARY KEY (`product_order_id`),
  INDEX `FK_buyer_productOrders_idx` (`buyer_id` ASC) VISIBLE,
  INDEX `FK_product_productOrders_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `FK_buyer_productOrders`
    FOREIGN KEY (`buyer_id`)
    REFERENCES `Buyer` (`buyer_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_product_productOrders`
    FOREIGN KEY (`product_id`)
    REFERENCES `Product` (`product_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShoppingCartProducts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ShoppingCartProducts` ;

CREATE TABLE IF NOT EXISTS `ShoppingCartProducts` (
  `shopping_cart_products_id` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT NULL,
  `shopping_cart_id` INT NULL,
  PRIMARY KEY (`shopping_cart_products_id`),
  INDEX `FK_product_shoppingCartProducts_idx` (`product_id` ASC) VISIBLE,
  INDEX `FK_shoppingCart_shoppingCartProducts_idx` (`shopping_cart_id` ASC) VISIBLE,
  CONSTRAINT `FK_product_shoppingCartProducts`
    FOREIGN KEY (`product_id`)
    REFERENCES `Product` (`product_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_shoppingCart_shoppingCartProducts`
    FOREIGN KEY (`shopping_cart_id`)
    REFERENCES `ShoppingCart` (`shopping_cart_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LogsInto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LogsInto` ;

CREATE TABLE IF NOT EXISTS `LogsInto` (
  `logs_into_id` INT NOT NULL AUTO_INCREMENT,
  `general_user_id` INT NOT NULL,
  `registered_user_id` INT NOT NULL,
  PRIMARY KEY (`logs_into_id`, `registered_user_id`, `general_user_id`),
  INDEX `FK_generalUser_registeredUser_idx` (`general_user_id` ASC) VISIBLE,
  INDEX `FK_registeredUser_logsInto_idx` (`registered_user_id` ASC) VISIBLE,
  CONSTRAINT `FK_generalUser_logsInto`
    FOREIGN KEY (`general_user_id`)
    REFERENCES `GeneralUser` (`general_user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_registeredUser_logsInto`
    FOREIGN KEY (`registered_user_id`)
    REFERENCES `RegisteredUser` (`registered_user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProductListings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProductListings` ;

CREATE TABLE IF NOT EXISTS `ProductListings` (
  `product_listing_id` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT NOT NULL,
  `marketplace_listing_id` INT NOT NULL,
  PRIMARY KEY (`product_listing_id`),
  INDEX `FK_marketplaceListing_productListings_idx` (`marketplace_listing_id` ASC) VISIBLE,
  INDEX `FK_product_productListings_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `FK_marketplaceListing_productListings`
    FOREIGN KEY (`marketplace_listing_id`)
    REFERENCES `MarketplaceListing` (`marketplace_listing_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_product_productListings`
    FOREIGN KEY (`product_id`)
    REFERENCES `Product` (`product_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
